services:
  - type: web
    name: frequencia
    env: python
    plan: free

    buildCommand: |
      python -m pip install --upgrade pip
      python -m pip install -r requirements.txt
      python -V && which python
      python -c "import sys; print('PY:', sys.executable)"
      python -c 'import django; print("Django:", django.get_version())'
      python -c "import shutil; shutil.rmtree('staticfiles', ignore_errors=True)"
      python manage.py findstatic admin/js/unusable_password_field.js
      python manage.py collectstatic --noinput --no-post-process

    startCommand: |
      ./.venv/bin/python manage.py migrate --noinput && \
      ./.venv/bin/python -m gunicorn frequencia.wsgi:application --bind 0.0.0.0:$PORT --access-logfile - --error-logfile - --log-level info

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
      - key: DEBUG
        value: "0"
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: WHITENOISE_STRICT
        value: "0"
