# Generated by Django 5.2.3 on 2025-08-20 13:32

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('descricao', models.CharField(max_length=100)),
                ('sabado_letivo', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('data',),
            },
        ),
        migrations.CreateModel(
            name='Prefeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Logo da prefeitura')),
            ],
            options={
                'verbose_name': 'Prefeitura',
                'verbose_name_plural': 'Prefeituras',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='SabadoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('data',),
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('cargo', models.CharField(max_length=50)),
                ('funcao', models.CharField(max_length=50)),
                ('data_admissao', models.DateField()),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('pis', models.CharField(blank=True, max_length=20, null=True)),
                ('titulo_eleitor', models.CharField(blank=True, max_length=20, null=True)),
                ('ctps_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('ctps_serie', models.CharField(blank=True, max_length=10, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=20, null=True)),
                ('escolaridade', models.CharField(blank=True, max_length=100, null=True)),
                ('tem_planejamento', models.BooleanField(default=False)),
                ('horario_planejamento', models.CharField(blank=True, max_length=50, null=True)),
                ('sabado_letivo', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_funcionarios/')),
                ('turma', models.CharField(blank=True, choices=[('A', 'Turma A'), ('B', 'Turma B'), ('C', 'Turma C'), ('D', 'Turma D'), ('E', 'Turma E'), ('F', 'Turma F'), ('G', 'Turma G')], max_length=10, null=True)),
                ('turno', models.CharField(blank=True, choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno'), ('Integral', 'Integral')], max_length=20, null=True)),
                ('serie', models.CharField(blank=True, choices=[('1º ANO', '1º ANO'), ('2º ANO', '2º ANO'), ('3º ANO', '3º ANO'), ('4º ANO', '4º ANO'), ('5º ANO', '5º ANO'), ('6º ANO', '6º ANO'), ('7º ANO', '7º ANO'), ('8º ANO', '8º ANO'), ('9º ANO', '9º ANO')], max_length=20, null=True)),
                ('tipo_vinculo', models.CharField(blank=True, choices=[('Efetivo', 'Efetivo'), ('Contratado', 'Contratado')], max_length=20, null=True)),
                ('fonte_pagadora', models.CharField(blank=True, max_length=100, null=True)),
                ('inicio_ferias', models.DateField(blank=True, null=True)),
                ('fim_ferias', models.DateField(blank=True, null=True)),
                ('is_chefe_setor', models.BooleanField(default=False, help_text='Marque se este servidor é a chefia imediata do setor.', verbose_name='Chefe do setor')),
                ('chefe_setor_desde', models.DateField(blank=True, help_text='Data a partir da qual é chefe do setor.', null=True, verbose_name='Chefe desde')),
                ('user', models.OneToOneField(blank=True, help_text='Vínculo opcional com usuário do sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='HorarioTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde')], max_length=10)),
                ('horario_inicio', models.TimeField(blank=True, null=True)),
                ('horario_fim', models.TimeField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Logo da secretaria')),
                ('prefeitura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secretarias', to='controle.prefeitura')),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
                'ordering': ('prefeitura__nome', 'nome'),
                'unique_together': {('prefeitura', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_secretaria', models.CharField(max_length=255)),
                ('nome_escola', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagem de fundo')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escolas', to='controle.secretaria')),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
                'ordering': ('nome_escola',),
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('ORGAO', 'Órgão vinculado'), ('ADMIN', 'Estrutura administrativa'), ('OUTRO', 'Outro')], default='ADMIN', max_length=10)),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departamentos', to='controle.escola')),
                ('prefeitura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departamentos', to='controle.prefeitura')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departamentos', to='controle.secretaria')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='AcessoSecretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('LEITURA', 'Leitura'), ('GERENCIA', 'Gerenciar (CRUD)')], default='LEITURA', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_secretaria', to=settings.AUTH_USER_MODEL)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='controle.secretaria')),
            ],
            options={
                'verbose_name': 'Acesso à Secretaria',
                'verbose_name_plural': 'Acessos às Secretarias',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='setores', to='controle.departamento')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='setores', to='controle.secretaria')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ('nome',),
            },
        ),
        migrations.AddField(
            model_name='funcionario',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.setor'),
        ),
        migrations.CreateModel(
            name='FuncaoPermissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_funcao', models.CharField(max_length=50)),
                ('nivel', models.CharField(choices=[('LEITURA', 'Leitura'), ('GERENCIA', 'Gerenciar (CRUD)')], default='LEITURA', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_funcao', to=settings.AUTH_USER_MODEL)),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permissoes_funcao', to='controle.secretaria')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permissoes_funcao', to='controle.setor')),
            ],
            options={
                'verbose_name': 'Permissão por Função',
                'verbose_name_plural': 'Permissões por Função',
            },
        ),
        migrations.CreateModel(
            name='AcessoSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('LEITURA', 'Leitura'), ('GERENCIA', 'Gerenciar (CRUD)')], default='LEITURA', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_setor', to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_setor', to='controle.setor')),
            ],
            options={
                'verbose_name': 'Acesso a Setor',
                'verbose_name_plural': 'Acessos a Setores',
            },
        ),
        migrations.CreateModel(
            name='UserScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('LEITURA', 'Leitura'), ('GERENCIA', 'Gerenciar (CRUD)')], default='LEITURA', max_length=16)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scopes', to='controle.departamento')),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scopes', to='controle.escola')),
                ('prefeitura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scopes', to='controle.prefeitura')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scopes', to='controle.secretaria')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scopes', to='controle.setor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escopo de Usuário',
                'verbose_name_plural': 'Escopos de Usuário',
            },
        ),
        migrations.CreateModel(
            name='AcessoEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('LEITURA', 'Leitura'), ('GERENCIA', 'Gerenciar (CRUD)')], default='LEITURA', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_escola', to=settings.AUTH_USER_MODEL)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_escola', to='controle.escola')),
            ],
            options={
                'verbose_name': 'Acesso à Unidade (Escola)',
                'verbose_name_plural': 'Acessos às Unidades (Escolas)',
                'unique_together': {('user', 'escola')},
            },
        ),
        migrations.CreateModel(
            name='FolhaFrequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('html_armazenado', models.TextField()),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.funcionario')),
            ],
            options={
                'ordering': ('funcionario__nome', 'ano', 'mes'),
                'unique_together': {('funcionario', 'mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='AcessoPrefeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('LEITURA', 'Leitura'), ('GERENCIA', 'Gerenciar (CRUD)')], default='LEITURA', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_prefeitura', to=settings.AUTH_USER_MODEL)),
                ('prefeitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_prefeitura', to='controle.prefeitura')),
            ],
            options={
                'verbose_name': 'Acesso à Prefeitura',
                'verbose_name_plural': 'Acessos à Prefeitura',
                'unique_together': {('user', 'prefeitura')},
            },
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('prefeitura__isnull', False), ('secretaria__isnull', True), ('escola__isnull', True)), models.Q(('prefeitura__isnull', True), ('secretaria__isnull', False), ('escola__isnull', True)), models.Q(('prefeitura__isnull', True), ('secretaria__isnull', True), ('escola__isnull', False)), _connector='OR'), name='departamento_exact_one_parent'),
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.UniqueConstraint(condition=models.Q(('prefeitura__isnull', False)), fields=('nome', 'prefeitura'), name='uniq_dep_nome_prefeitura'),
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.UniqueConstraint(condition=models.Q(('secretaria__isnull', False)), fields=('nome', 'secretaria'), name='uniq_dep_nome_secretaria'),
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.UniqueConstraint(condition=models.Q(('escola__isnull', False)), fields=('nome', 'escola'), name='uniq_dep_nome_escola'),
        ),
        migrations.AlterUniqueTogether(
            name='acessosecretaria',
            unique_together={('user', 'secretaria')},
        ),
        migrations.AddConstraint(
            model_name='setor',
            constraint=models.CheckConstraint(condition=models.Q(('departamento__isnull', False), ('secretaria__isnull', False), _connector='OR'), name='setor_has_parent'),
        ),
        migrations.AddConstraint(
            model_name='funcionario',
            constraint=models.UniqueConstraint(condition=models.Q(('is_chefe_setor', True)), fields=('setor',), name='uniq_chefe_por_setor'),
        ),
        migrations.AlterUniqueTogether(
            name='funcaopermissao',
            unique_together={('user', 'nome_funcao', 'nivel', 'secretaria', 'setor')},
        ),
        migrations.AlterUniqueTogether(
            name='acessosetor',
            unique_together={('user', 'setor')},
        ),
        migrations.AddConstraint(
            model_name='userscope',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('prefeitura__isnull', False), ('secretaria__isnull', True), ('escola__isnull', True), ('departamento__isnull', True), ('setor__isnull', True)), models.Q(('prefeitura__isnull', True), ('secretaria__isnull', False), ('escola__isnull', True), ('departamento__isnull', True), ('setor__isnull', True)), models.Q(('prefeitura__isnull', True), ('secretaria__isnull', True), ('escola__isnull', False), ('departamento__isnull', True), ('setor__isnull', True)), models.Q(('prefeitura__isnull', True), ('secretaria__isnull', True), ('escola__isnull', True), ('departamento__isnull', False), ('setor__isnull', True)), models.Q(('prefeitura__isnull', True), ('secretaria__isnull', True), ('escola__isnull', True), ('departamento__isnull', True), ('setor__isnull', False)), _connector='OR'), name='userscope_exact_one_target'),
        ),
        migrations.AlterUniqueTogether(
            name='userscope',
            unique_together={('user', 'prefeitura', 'secretaria', 'escola', 'departamento', 'setor')},
        ),
    ]
