# Generated by Django 5.2.3 on 2025-08-21 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='chefe',
            field=models.ForeignKey(blank=True, help_text='Servidor que exerce a chefia deste setor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chefias_de_setor', to='controle.funcionario'),
        ),
    ]
