# Generated by Django 5.2.3 on 2025-08-20 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecessoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=120, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recessos', to='controle.funcionario')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recessos', to='controle.setor')),
            ],
            options={
                'verbose_name': 'Recesso de Funcionário',
                'verbose_name_plural': 'Recessos de Funcionários',
                'indexes': [models.Index(fields=['funcionario', 'data_inicio', 'data_fim'], name='controle_re_funcion_44949d_idx'), models.Index(fields=['setor', 'data_inicio', 'data_fim'], name='controle_re_setor_i_e733a5_idx')],
            },
        ),
    ]
