# Generated by Django 5.2.3 on 2025-08-22 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_orgao_bairro_orgao_cep_orgao_cidade_orgao_endereco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('categoria', models.CharField(choices=[('PLANEJAMENTO', 'Planejamento'), ('FERIADO', 'Feriado'), ('RECESSO', 'Recesso'), ('REUNIAO', 'Reunião'), ('AVALIACAO', 'Avaliação'), ('AULA', 'Aula'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('orgao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='controle.orgao')),
            ],
            options={
                'ordering': ('data_inicio', 'titulo'),
            },
        ),
    ]
