# Generated by Django 5.2.3 on 2025-08-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0004_alter_calendarioevento_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarioevento',
            name='categoria',
            field=models.CharField(choices=[('PLANEJAMENTO', 'Planejamento'), ('REUNIAO', 'Reunião'), ('AVALIACAO', 'Avaliação'), ('AULA', 'Aula'), ('OUTRO', 'Outro'), ('NAO_LETIVO', 'Férias / Recesso / Feriado'), ('MATRICULAS', 'Matrículas'), ('AULA_INAUGURAL', 'Aula inaugural'), ('INICIO_BIMESTRE', 'Início das aulas no bimestre'), ('CONSELHO_PEDAGOGICO', 'Conselho de classe/pedagógico'), ('PPP_AVALIACAO', 'PPP — Avaliação'), ('FORMACAO_TURMAS', 'Formação de turmas'), ('FORMATURAS', 'Formaturas escolares'), ('AVALIACAO_DIAGNOSTICA', 'Avaliação diagnóstica'), ('RECUPERACOES_FINAIS', 'Recuperações finais'), ('SAETO', 'SAETO'), ('INDEPENDENCIA_BRASIL', 'Independência do Brasil'), ('FORMACOES_CONTINUADAS', 'Formações continuadas (rede)'), ('DATAS_COMEMORATIVAS', 'Datas comemorativas')], default='OUTRO', max_length=32),
        ),
    ]
